# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 22:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadedComment',
            fields=[
                ('comment_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True, primary_key=True,
                    serialize=False, to='django_comments.Comment')),
                ('lft', models.PositiveIntegerField(
                    db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(
                    db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(
                    db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(
                    db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='children',
                    to='zinnia-threaded-comments.ThreadedComment',
                    verbose_name='reply in comment')),
            ],
            options={
                'abstract': False,
            },
            bases=('django_comments.comment', models.Model),
        ),
    ]
